name: lidar-camera-road-autolabeling
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch=2.5.0
  - torchvision=0.20
  - pytorch-cuda=12.4
  - conda-forge::pydensecrf
  - tqdm
  - pip
  - pip:
    - opencv-python
    - open3d
    - utm
